window.MATCHES = [
  {
    id: "grp-a-1",
    group: "A",
    stage: "gruppespill",
    datetime: "2026-06-11T21:00:00+02:00",
    dateLabel: "11. juni",
    timeLabel: "21:00",
    broadcaster: "TV 2",
    home: { name: "Mexico", code: "MEX" },
    away: { name: "Sør-Afrika", code: "ZAF" },
    venue: "Mexico City",
  },
  {
    id: "grp-a-2",
    group: "A",
    stage: "gruppespill",
    datetime: "2026-06-12T03:00:00+02:00",
    dateLabel: "12. juni",
    timeLabel: "03:00",
    broadcaster: "NRK",
    home: { name: "Sør-Korea", code: "KOR" },
    away: { name: "Canada", code: "CAN" },
    venue: "Guadalajara",
  },
  {
    id: "grp-a-3",
    group: "A",
    stage: "gruppespill",
    datetime: "2026-06-17T21:00:00+02:00",
    dateLabel: "17. juni",
    timeLabel: "21:00",
    broadcaster: "TV 2",
    home: { name: "Mexico", code: "MEX" },
    away: { name: "Sør-Korea", code: "KOR" },
    venue: "Mexico City",
  },
  {
    id: "grp-a-4",
    group: "A",
    stage: "gruppespill",
    datetime: "2026-06-17T21:00:00+02:00",
    dateLabel: "17. juni",
    timeLabel: "21:00",
    broadcaster: "NRK",
    home: { name: "Sør-Afrika", code: "ZAF" },
    away: { name: "Canada", code: "CAN" },
    venue: "Monterrey",
  },
  {
    id: "grp-b-1",
    group: "B",
    stage: "gruppespill",
    datetime: "2026-06-13T21:00:00+02:00",
    dateLabel: "13. juni",
    timeLabel: "21:00",
    broadcaster: "TV 2",
    home: { name: "Canada", code: "CAN" },
    away: { name: "Qatar", code: "QAT" },
    venue: "Vancouver",
  },
  {
    id: "grp-b-2",
    group: "B",
    stage: "gruppespill",
    datetime: "2026-06-14T03:00:00+02:00",
    dateLabel: "14. juni",
    timeLabel: "03:00",
    broadcaster: "NRK",
    home: { name: "Sveits", code: "CHE" },
    away: { name: "Brasil", code: "BRA" },
    venue: "Toronto",
  },
  {
    id: "grp-b-3",
    group: "B",
    stage: "gruppespill",
    datetime: "2026-06-18T21:00:00+02:00",
    dateLabel: "18. juni",
    timeLabel: "21:00",
    broadcaster: "TV 2",
    home: { name: "Brasil", code: "BRA" },
    away: { name: "Qatar", code: "QAT" },
    venue: "Philadelphia",
  },
  {
    id: "grp-c-1",
    group: "C",
    stage: "gruppespill",
    datetime: "2026-06-15T21:00:00+02:00",
    dateLabel: "15. juni",
    timeLabel: "21:00",
    broadcaster: "NRK",
    home: { name: "Marokko", code: "MAR" },
    away: { name: "Haiti", code: "HTI" },
    venue: "New York",
  },
  {
    id: "grp-c-2",
    group: "C",
    stage: "gruppespill",
    datetime: "2026-06-16T03:00:00+02:00",
    dateLabel: "16. juni",
    timeLabel: "03:00",
    broadcaster: "TV 2",
    home: { name: "Skottland", code: "SCO" },
    away: { name: "Brasil", code: "BRA" },
    venue: "Boston",
  },
  {
    id: "grp-c-3",
    group: "C",
    stage: "gruppespill",
    datetime: "2026-06-20T21:00:00+02:00",
    dateLabel: "20. juni",
    timeLabel: "21:00",
    broadcaster: "NRK",
    home: { name: "Marokko", code: "MAR" },
    away: { name: "Skottland", code: "SCO" },
    venue: "Miami",
  },
  {
    id: "grp-c-4",
    group: "C",
    stage: "gruppespill",
    datetime: "2026-06-20T21:00:00+02:00",
    dateLabel: "20. juni",
    timeLabel: "21:00",
    broadcaster: "TV 2",
    home: { name: "Haiti", code: "HTI" },
    away: { name: "Brasil", code: "BRA" },
    venue: "Atlanta",
  },
];
